name: object_key
description: A tiny library for Objects and Keys.
version: 0.1.1
homepage: https://github.com/moky/ObjectKey
repository: https://github.com/moky/ObjectKey
issue_tracker: https://github.com/moky/ObjectKey/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
